> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Numpy functions i found cool!


### Introduction

Write a short introduction about Numpy and list the chosen functions. 
Numpy is a module that is helpful creating datatypes that are extremely fast and efficient

- np.arange
- np.transpose
- np.delete
- np.append
- np.fromstring

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [6]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "christian-cisneros-f/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/christian-cisneros-f/numpy-array-operations


'https://jovian.ai/christian-cisneros-f/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [7]:
# List of functions explained 
function1 = np.arange
function2 = np.transpose
function3 = np.delete
function4 = np.append
function5 = np.fromstring

## Function 1 - np.arange

Creates an array that starts from its first parameter up to second parameters but not included,where the step is the third parameter

In [ ]:
# Example 1 - working (change this)
#Create an array of not negatives even numbers up to certain number n
n=14
array1=np.arange(0,n+1,2)
array1


Explanation about example
Created an array that starts from 0 up to n+1 because we want to include n which in this case is 14, since we want even numbers and it starts from 0, the step is 2

In [ ]:
# Example 2 - working
#Create an array of not negatives odd numbers up to certain number m
m=15
array1=np.arange(1,m+1,2)
array1

Explanation about example
Created an array that starts from 0 up to m+1 because we want to include m which in this case is 15, since we want odd numbers and it starts from 1, the step is 2

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
array1=np.arange(1,10,0)
array1

ZeroDivisionError: division by zero

Explanation about example (why it breaks and how to fix it)
You can't put step=0 since it wont affect the start
You can change the step to any number

Some closing comments about when to use this function.
This function is useful since you dont have to type a lot of code to write values that have an arithmetic progression

In [42]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "christian-cisneros-f/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/christian-cisneros-f/numpy-array-operations


'https://jovian.ai/christian-cisneros-f/numpy-array-operations'

## Function 2 - np.transpose

Inverts the axes of an array

In [43]:
# Example 1 - working
array4= np.arange(9).reshape(3,3)
print(array4,"\n")

print(np.transpose(array4))

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 3 6]
 [1 4 7]
 [2 5 8]]


Explanation about example

In [ ]:
# Example 2 - working
#You can check what happens to the shape of a transpose matrix
array5= np.zeros((1,3,4))
print(array5.shape)

print(np.transpose(array5).shape)


Explanation about example

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.arange(12).reshape(2,2,3)
print(x)

new= np.transpose(x,(2,1,3))
print(new)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


AxisError: axis 3 is out of bounds for array of dimension 3

Explanation about example (why it breaks and how to fix it)
When using np.transpose , its second parameter if used it has to be a list or tuple of permutations from 0 to number of axis-1
in this case we can choose from 0 to 2
new= np.transpose(x,(2,1,0)) <- fixed

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Function 3 - np.delete

Add some explanations

In [40]:
# Example 1 - working
array6 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]
np.delete(array6,1,0)

SyntaxError: invalid syntax (3083040875.py, line 3)

Will delete the second row

In [39]:
# Example 2 - working
array7 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.delete(array6,1,1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

Will delete the second column

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
array6 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.delete(array6,4,1)

IndexError: index 4 is out of bounds for axis 1 with size 4

Explanation about example (why it breaks and how to fix it)
Second parameter cant be four because there are only 4 columns and its maximum index is 3
if we were to choose rows(third parameter) its index max value is 2

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Function 4 - np.append

Add some explanations

In [37]:
# Example 1 - working
#can be used to also create an array
np.append([1,3,5],[[7,9,11,13,15,17]])


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

here the array we had is [1,3,5] then we added 7,  9, 11, 13, 15, 17

In [36]:
# Example 2 - working
#you can also put the variable name in the first parameter
array8=np.arange(6)
print(array8)
#add values 
np.append(array8,[[5,7,8]])

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5, 5, 7, 8])

Explanation about example

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
ar3=[[2,3,4],
     [5,6,7]]
print(np.shape(ar3))
np.append(ar3,[2,3,5],axis=0

SyntaxError: unexpected EOF while parsing (4088427413.py, line 5)

Explanation about example (why it breaks and how to fix it)
must be the same shape as ar3

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Function 5 - np.fromstring

Creates an 1d array extracting string type data

In [45]:
# Example 1 - working
text="1,2,3,4"
ar=np.fromstring(text,dtype=int,sep=",")
ar

array([1, 2, 3, 4])

Explanation about example

In [44]:
# Example 2 - working
#you can combinite it with reshape to make a 2d array
text1="1,2,3,4,5,6,7,8,9"
ar2=np.fromstring(text,dtype=int,sep=",")
np.reshape(ar2,(3,3))

NameError: name 'text' is not defined

Explanation about example

In [46]:
# Example 3 - breaking (to illustrate when it breaks)
text3="1,2,3,4,5,6,7,8,9"
ar2=np.fromstring(text,dtype=int,sep=" ")
ar2

/tmp/ipykernel_85/681023016.py:3: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  ar2=np.fromstring(text,dtype=int,sep=" ")


array([1])

Explanation about example (why it breaks and how to fix it)
You have to give a proper separator
"," in this case

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Conclusion

in this notebook i had to find which functions i found useful and had to search a lot to find them.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()